### ISSUE TITLE
Scan Key Codes Work in Qemu??

### ISSUE THREAD

**Issue by davidm71** [NikolajSchlej/CrScreenshotDxe#1]
Hi,

Cant get this to work in Qemu in that pressing the ctrl-f12-alt combination doesnt do anything. Is this because of Qemu not translating key presses?

Thanks

**Comment by NikolajSchlej** [comment]
Make sure that the driver is loaded successfully (i.e. you can see the white rectangle). You can also try to change the key combination and rebuild the driver with newer EDK2.

**Comment by btwise** [comment]
How to integrate it into a UEFI bootloader  like OpenCore?
