### ISSUE TITLE
How to load???

### ISSUE THREAD

**Issue by 1457384613gh** [NikolajSchlej/CrScreenshotDxe#2]
I'm sorry but I fail to load it.
Can you tell me more details about how to take a screenshot when EFI grub2 displaying???

**Comment by dnchshrp** [comment]
- If you want the driver to always load:
1. copy the driver .efi file to somewhere
2. boot into efi shell(if it's not integrated into your uefi you can download it in the internet)
3. run this command:

bcfg driver add 0 path\to\driver\CrScreenshotDxe.efi "CrScreenshotDxe.efi"
(you can replace 0 with different number)

Congrats! Now the driver will automatially load every time you boot your PC
To remove it run "bcfg driver rm 0" (you need to replace 0 with the number you used in the previous step)

- If you want to temporarily load the driver:
1. copy the driver .efi file to somewhere
2. boot into efi shell(if it's not integrated into your uefi you can download it in the internet)
3. navigate to the driver folder
4. run "load CrScreenshotDxe.efi"
5. navigate to the folder where your bootloader is placed
6. run the efi file of your bootloader

**Comment by Gelip** [comment]
If you want take screenshot of CMOS Setup:

- copy CrScreenshootDxe.efi to FAT32 USB stick
- boot to CMOS Setup then load UEFI Shell from USB or from Built-in
![Save_Exit](https://github.com/user-attachments/assets/57c39b1e-c27f-4ceb-8259-f73cfe1518b2)
- load CrScreenshootDxe.efi
- exit - this back to CMOS Setup
- now possible press LCtrl + LAlt + F12 to make screenshot of current display screen
P. S. It's best to disconnect all other disks and drives, leaving only a pendrive to make the **exit** command to go to CMOS Setup
![Boot](https://github.com/user-attachments/assets/efe252b3-5d28-4897-b17e-6a5c34c2e425)
![Advanced](https://github.com/user-attachments/assets/27e59263-4c20-4595-8149-a1852de881eb)
